services:
  - type: web
    name: sweetbox-synthage
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn SweetBoxSYNTHAGE.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: SweetBoxSYNTHAGE.settings 