# Generated by Django 4.2.18 on 2025-07-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Mark this preset as private'),
        ),
    ]
