# Generated by Django 4.2.18 on 2025-07-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0002_preset_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='channel',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='knob',
            name='channel',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='preset',
            name='has_joystick',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='preset',
            name='keys_channel',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='preset',
            name='number_of_buttons',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='preset',
            name='number_of_knobs',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='keys_channel',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
