# Generated by Django 4.2.18 on 2025-07-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0003_alter_button_channel_alter_knob_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='has_joystick',
            field=models.BooleanField(default=False),
        ),
    ]
