# Generated by Django 4.2.18 on 2025-07-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0004_alter_preset_has_joystick'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Default privacy setting for new presets'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='keys_channel',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
