# Generated by Django 4.2.18 on 2025-07-07 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0021_alter_knob_pin_alter_preset_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='number_of_buttons',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.PositiveSmallIntegerField(default=1, null=True)),
                ('mode', models.CharField(choices=[('note', 'Note'), ('cc', 'Control Change')], default='note', max_length=4)),
                ('noteCC', models.PositiveSmallIntegerField(default=0, help_text='Note number or CC number depending on mode')),
                ('velocityMin', models.IntegerField(default=100, help_text='Velocity for notes or minimum CC value')),
                ('max', models.IntegerField(default=127, help_text='Maximum CC value (only used in CC mode)')),
                ('pin', models.IntegerField(default=0)),
                ('preset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='midi.preset')),
            ],
        ),
    ]
