# Generated by Django 4.2.18 on 2025-07-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0022_preset_number_of_buttons_button'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModWheel',
        ),
        migrations.DeleteModel(
            name='PitchWheel',
        ),
        migrations.AddField(
            model_name='joystick',
            name='x_cc',
            field=models.PositiveSmallIntegerField(blank=True, help_text='CC number for X-axis (only used in CC mode)', null=True),
        ),
        migrations.AddField(
            model_name='joystick',
            name='x_channel',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='joystick',
            name='x_mode',
            field=models.CharField(choices=[('pitch', 'Pitch Bend'), ('cc', 'Control Change')], default='pitch', max_length=5),
        ),
        migrations.AddField(
            model_name='joystick',
            name='x_pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joystick',
            name='y_cc',
            field=models.PositiveSmallIntegerField(default=2, help_text='CC number for Y-axis'),
        ),
        migrations.AddField(
            model_name='joystick',
            name='y_channel',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='joystick',
            name='y_pin',
            field=models.IntegerField(default=1),
        ),
    ]
