# Generated by Django 4.2.18 on 2025-07-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midi', '0023_delete_modwheel_delete_pitchwheel_joystick_x_cc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='has_joystick',
            field=models.BooleanField(default=False),
        ),
    ]
