# Generated by Django 4.2.18 on 2025-07-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board',
            new_name='name',
        ),
    ]
