# Generated by Django 4.2.18 on 2025-07-25 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_rename_board_board_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
