# Generated by Django 4.2.18 on 2025-07-14 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys_channel', models.PositiveSmallIntegerField(default=1)),
                ('number_of_knobs', models.PositiveSmallIntegerField(default=4)),
                ('number_of_buttons', models.PositiveSmallIntegerField(default=0)),
                ('has_joystick', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False, help_text='Default privacy setting for new presets')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
